In [1]:
import volpick.data
import volpick
from obspy.clients.fdsn import Client
from obspy import UTCDateTime
import matplotlib.pyplot as plt
import os
import pandas as pd
import numpy as np
import time
import datetime
from pathlib import Path
from obspy import read
from collections import namedtuple
from volpick.data.utils import freqency_index, extract_events

volpick.cache_root = Path("/home/zhongyiyuan/DATA/my_data")

In [2]:
data_dir = Path("/home/zhongyiyuan/DATA/LP_catalog/Cascade/VTs")

In [3]:
df_list = []
for x in data_dir.iterdir():
    df = pd.read_csv(x)
    n0 = 100
    if len(df) > n0:
        idx = np.sort(
            np.random.default_rng(seed=50).choice(len(df), size=n0, replace=False)
        )
        df = df.iloc[idx].copy()
    df_list.append(df)

In [4]:
[len(x) for x in df_list]

[100, 100, 100, 100, 100, 100, 100, 64, 8, 100]

In [5]:
concat_df = pd.concat(df_list, ignore_index=True)
concat_df

,Evid,Magnitude,Magnitude Type,Epoch(UTC),Time UTC,Time Local,Distance From,Lat,Lon,Depth Km,Depth Mi
0,61980296,2.1,l,1.705530e+09,2024/01/17 22:14:32,2024/01/17 14:14:32 PST,"3.1 km from Mt Adams, WA",46.1928,-121.5215,5.5,3.4
1,61973246,1.4,l,1.700507e+09,2023/11/20 18:59:18,2023/11/20 10:59:18 PST,"2.8 km from Mt Adams, WA",46.2043,-121.5187,2.8,1.7
2,61877147,1.0,l,1.664994e+09,2022/10/05 18:17:27,2022/10/05 11:17:27 PDT,"0.5 km from Mt Adams, WA",46.2048,-121.4835,0.2,0.1
3,61884366,0.6,l,1.664350e+09,2022/09/28 07:18:38,2022/09/28 00:18:38 PDT,"29.6 km from Mt Adams, WA",46.3873,-121.7568,6.5,4.0
4,61827571,0.8,l,1.648972e+09,2022/04/03 07:52:49,2022/04/03 00:52:49 PDT,"18.0 km from Goat Rocks, WA",46.4285,-121.6467,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
867,10160963,2.0,d,4.245832e+08,1983/06/16 03:46:08,1983/06/15 20:46:08 PDT,"10.2 km from Concrete, WA",48.6167,-121.8242,-0.5,-0.3
868,10111358,0.9,d,3.616581e+08,1981/06/17 20:34:33,1981/06/17 13:34:33 PDT,"17.5 km from Mt Baker, WA",48.6637,-121.9828,0.0,0.0
869,10111343,1.3,d,3.616539e+08,1981/06/17 19:24:31,1981/06/17 12:24:31 PDT,"16.3 km from Mt Baker, WA",48.6575,-121.9462,-0.8,-0.5
870,10110263,1.8,d,3.611748e+08,1981/06/12 06:20:49,1981/06/11 23:20:49 PDT,"16.1 km from Mt Baker, WA",48.6532,-121.9332,-0.8,-0.5
871,10106588,1.5,d,3.599108e+08,1981/05/28 15:13:06,1981/05/28 08:13:06 PDT,"17.9 km from Concrete, WA",48.6345,-121.9448,-0.8,-0.5

In [6]:
idx = np.sort(
    np.random.default_rng(seed=50).choice(len(concat_df), size=300, replace=False)
)

sampled_vts = concat_df.iloc[idx].copy()
sampled_vts.to_csv(
    "/home/zhongyiyuan/DATA/LP_catalog/Cascade/downsampled_VT.csv", index=False
)

In [25]:
df = pd.read_csv("/home/zhongyiyuan/DATA/my_data/Cascade_vt/mseed_log/downloads.csv")
print(len(df))
print(len(np.unique(df["source_id"])))

eids = df.drop_duplicates(
    subset="source_id", keep="first", ignore_index=True, inplace=False
)["source_id"]

rand_events_idxs = np.sort(
    np.random.default_rng(seed=90).choice(eids, size=240, replace=False)
)
rand_events_table = df[df["source_id"].isin(rand_events_idxs)].copy()
print(len(rand_events_table))

957
246
941

In [26]:
df = pd.read_csv("/home/zhongyiyuan/DATA/my_data/Cascade_lp/mseed_log/downloads.csv")
print(len(df))
print(len(np.unique(df["source_id"])))

810
201